
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: odoo
  namespace: openshift-gitops
spec:
  project: default

  source:
    repoURL: https://github.com/talhazafarsb/odoo.git
    targetRevision: main
    path: deployment/

  destination:
    server: https://kubernetes.default.svc
    namespace: odoo

  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
